# Generated by Django 2.0.2 on 2018-02-06 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_salesgroup_salesstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('sales_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.SalesStage')),
            ],
        ),
    ]
