# Generated by Django 2.0.2 on 2018-02-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
