# Generated by Django 2.0.2 on 2018-02-07 03:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_communication_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='values',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
    ]
