# Generated by Django 2.0.2 on 2018-02-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_communication_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='values',
        ),
    ]
