# Generated by Django 2.0.2 on 2018-02-07 05:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_remove_communication_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
    ]
