# Generated by Django 2.0.2 on 2018-02-07 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_communication_fields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesStage',
            new_name='SubStage',
        ),
    ]
