# Generated by Django 2.0.2 on 2018-02-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20180207_0531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='communication',
            new_name='last_communication',
        ),
    ]
