# Generated by Django 2.0.2 on 2018-02-07 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_bottomed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bottomed',
            name='age',
        ),
        migrations.RemoveField(
            model_name='bottomed',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bottomed',
            name='name',
        ),
        migrations.AddField(
            model_name='bottomed',
            name='commoninfo_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.CommonInfo'),
            preserve_default=False,
        ),
    ]
