# Generated by Django 2.0.2 on 2018-02-07 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20180207_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottomed',
            name='commoninfo_ptr',
        ),
        migrations.DeleteModel(
            name='Bottomed',
        ),
        migrations.DeleteModel(
            name='CommonInfo',
        ),
    ]
