# Generated by Django 2.0.2 on 2018-02-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_auto_20180207_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottomed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('headline',),
            },
        ),
        migrations.CreateModel(
            name='Par',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='bottomed',
            name='pars',
            field=models.ManyToManyField(to='client.Par'),
        ),
    ]
