# Generated by Django 2.0.2 on 2018-02-07 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_auto_20180207_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.LeadPost'),
            preserve_default=False,
        ),
    ]
