# Generated by Django 2.0.2 on 2018-02-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20180207_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottomed',
            name='pars',
        ),
        migrations.DeleteModel(
            name='Bottomed',
        ),
        migrations.DeleteModel(
            name='Par',
        ),
    ]
