# Generated by Django 2.0.2 on 2018-02-07 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20180207_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='client',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='sales_stage',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='client',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_communication',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lead_post',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lead_stage',
        ),
        migrations.RemoveField(
            model_name='substage',
            name='sales_group',
        ),
        migrations.DeleteModel(
            name='Communication',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.DeleteModel(
            name='LeadPost',
        ),
        migrations.DeleteModel(
            name='LeadStage',
        ),
        migrations.DeleteModel(
            name='SalesGroup',
        ),
        migrations.DeleteModel(
            name='SubStage',
        ),
    ]
