# Generated by Django 2.0.2 on 2018-02-08 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(choices=[('Outbound Call', 'Outbound Call'), ('Inbound Call', 'Inbound Call'), ('Inbound Email', 'Inbound Email'), ('Outbound Email', 'Outbound Email'), ('SMS', 'SMS'), ('Meeting', 'Meeting')], max_length=100)),
                ('medium_direction', models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], max_length=100)),
                ('medium_status', models.CharField(choices=[('Successful', 'Successful'), ('Unsuccessful', 'Unsuccessful')], max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.ContactPerson')),
            ],
        ),
        migrations.CreateModel(
            name='SalesGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sales_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.SalesGroup')),
            ],
        ),
        migrations.AddField(
            model_name='communication',
            name='sales_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.SubStage'),
        ),
    ]
