# Generated by Django 2.0.2 on 2018-02-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='contact_person',
            field=models.CharField(default='Ram', max_length=255),
            preserve_default=False,
        ),
    ]
