# Generated by Django 2.0.2 on 2018-02-07 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_communication_contact_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='substage',
            name='enable_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communication',
            name='reminder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='communication.Reminder'),
            preserve_default=False,
        ),
    ]
