# Generated by Django 2.0.2 on 2018-02-07 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_auto_20180207_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='communication',
            name='contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.ContactPerson'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
