# Generated by Django 2.0.2 on 2018-02-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_auto_20180207_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substage',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='substage',
            name='set_reminder',
        ),
        migrations.AddField(
            model_name='communication',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='set_reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
