# Generated by Django 2.0.2 on 2018-02-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_auto_20180207_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
