# Generated by Django 2.0.2 on 2018-02-08 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('client_value', models.CharField(choices=[('High', 'High'), ('Mid', 'Mid'), ('Low', 'Low')], max_length=15)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
        ),
        migrations.CreateModel(
            name='LeadPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SalesLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.Communication')),
                ('lead_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.Lead')),
                ('lead_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.LeadStage')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='post_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.LeadPost'),
        ),
    ]
