# Generated by Django 2.0.2 on 2018-02-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='last_communication',
            new_name='communication',
        ),
    ]
