# Generated by Django 2.0.2 on 2018-02-08 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_auto_20180207_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='amount',
            field=models.ForeignKey(default=25000, on_delete=django.db.models.deletion.CASCADE, to='lead.Amount'),
            preserve_default=False,
        ),
    ]
